name: "Readme update Actions"
description: "Fetch latest blog posts and add it to GitHub profile's readme dynamically"
author: "Shubham Kumar"
inputs:
  rss_list:
    description: "RSS feed url"
    default: ""
    required: true
  readme_path:
    description: "Path of readme file"
    default: "./README.md"
    required: false
  max_post:
    description: "Max number of posts"
    default: "3"
    required: false
  commit_user:
    description: "Git username"
    default: "readme-update-bot"
    required: false
  commit_email:
    description: "Git user email"
    default: "readme-update-actions@example.com"
    required: false
  commit_message:
    description: "Git commit message"
    default: "Update readme with latest blogs"
    required: false
outputs:
  result_post:
    description: "Stringified posts in readme format"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - run: go run ${{ github.action_path }}/main.go
      shell: bash

    - run: go run ${{ github.action_path }}/main.go
      shell: bash
  # args:
  # - "-rss_list=${{ inputs.rss_list }}"
  # - "-commit_user=${{ inputs.commit_user }}"
  # - "-commit_email=${{ inputs.commit_email }}"
  # - "-commit_message=${{ inputs.commit_message }}"

branding:
  icon: 'file-text'
  color: 'red'